### ISSUE TITLE
API for NLP stuff

### ISSUE THREAD

**Issue by hbredin** [PaulLerner/pyannote-db-plumcot#12]
Before releasing the corpus, we should provide example on how to load transcripts (and their forced-aligned version when available).

This probably means that we need to implement a dedicated API for that in the pyannote.database plugin.

```python
>>> from pyannote.database import get_protocol
>>> protocol = get_protocol('TheBigBangTheory.????.Transcription')
>>> for file in protocol.train():
...    transcription = file['transcription']
...    for line in transcription:
...       line['speaker']
...       line['text'] 
...       # other fields of interest? time?
```

**Comment by PaulLerner** [comment]
I've implemented something to load and align forced-aligned transcripts and entity linking stuff in an `Annotation` here: https://github.com/PaulLerner/pyannote-audio/blob/a77abf7045ca100d1736c3820e077a44830af794/pyannote/audio/pipeline/ASR.py

I only tested it with TheOffice for now, there might be some issues because:
- entity linking stuff were tokenized in a weird, inconsistent, way
- some `aligned` files relies on old versions of my code and might have to be updated (see, e.g. https://github.com/PaulLerner/pyannote-db-plumcot/commit/e638bb820d6f934e5bb828f8262d4b768c45d22c#diff-3899bff8e1ee638c3a5e28f71c3b22c2R165)

**Comment by hbredin** [comment]
I don't think `Annotation` is the best data structure because:
* the whole "label" thing does not make sense for transcripts. 
* hence the [internal data structure](https://github.com/pyannote/pyannote-core/blob/278338a515f6408ecfdd6cdf10e6b406ae25eff9/pyannote/core/annotation.py#L163-L171) adds useless and computationally-heavy complexity 

What about[ `spacy` data structures](https://spacy.io/api/doc)?

**Comment by hbredin** [comment]
In all case each token should have a 'speaker' field (which might be set to `unavailable`)

If the transcript is a '.aligned' file, several fields could be added:
- token start time
- token end time
- token alignment confidence

If the entity annotation is provided we could add (I guess those already exists in spacy):
- POS tag
- dependency
- entity type

_Originally posted by @PaulLerner  in https://github.com/pyannote/pyannote-database/issues/48#issue-617563972_

**Comment by hbredin** [comment]
I've had a quick look at spaCy `Doc` and `Token` objects and they do provide an [*extension*](https://spacy.io/usage/processing-pipelines#custom-components-attributes) API that could be used to add those fields and even methods to convert from/to `pyannote.core` objects when it makes sense.

**Comment by hbredin** [comment]
FYI, [back in the days](https://github.com/pyannote/pyannote-core/commit/1d232d5036a70cfe466ba5a710e26a72a66f4fa6), `pyannote.core` had a very bad `Transcription` data structure.

**Comment by hbredin** [comment]
See https://github.com/pyannote/pyannote-core/blob/331f2fb2751c4c0fe09cce73aaf62e53afd8f1f2/notebook/pyannote.core.transcription.ipynb for more.
